# Gives every stylesheet and script in index.html a fresh ?v= stamp, so a browser
# never mixes cached old files with new ones after an update. Run before each
# commit that changes anything in src/:
#   powershell -ExecutionPolicy Bypass -File tools\stamp-version.ps1
# It rewrites the block between the version:start / version:end markers in
# index.html: the stylesheets (same order), an import map that stamps every
# module under src/, and the main.js script tag.

$root = Split-Path -Parent $PSScriptRoot
$indexPath = Join-Path $root 'index.html'
$utf8 = New-Object System.Text.UTF8Encoding($false)
$html = [IO.File]::ReadAllText($indexPath, [Text.Encoding]::UTF8)
$nl = if ($html.Contains("`r`n")) { "`r`n" } else { "`n" }

$m = [regex]::Match($html, '(?s)<!-- version:start.*?<!-- version:end -->')
if (-not $m.Success) { throw 'version markers not found in index.html' }

$v = Get-Date -Format 'yyyyMMddHHmm'
$css = [regex]::Matches($m.Value, 'href="(src/styles/[^"?]+)') | ForEach-Object { $_.Groups[1].Value }
$modules = Get-ChildItem (Join-Path $root 'src') -Recurse -Filter *.js |
  ForEach-Object { 'src/' + $_.FullName.Substring((Join-Path $root 'src').Length + 1).Replace('\', '/') } |
  Sort-Object

$lines = @('<!-- version:start (generated by tools/stamp-version.ps1) -->')
$lines += $css | ForEach-Object { "<link rel=`"stylesheet`" href=`"$_`?v=$v`">" }
$lines += '<script type="importmap">'
$lines += '{ "imports": {'
$entries = $modules | ForEach-Object { "  `"./$_`": `"./$_`?v=$v`"" }
$lines += ($entries -join (',' + $nl))
$lines += '} }'
$lines += '</script>'
$lines += "<script type=`"module`" src=`"src/main.js?v=$v`"></script>"
$lines += '<!-- version:end -->'

$html = $html.Substring(0, $m.Index) + ($lines -join $nl) + $html.Substring($m.Index + $m.Length)
[IO.File]::WriteAllText($indexPath, $html, $utf8)
"Stamped version $v ($($css.Count) stylesheets, $($modules.Count) modules)"
